blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/0x6flab/nairobi-traffic-pcb/discussions
    about: Join in-depth discussions about the nairobi-traffic-pcb project. Ask questions, share your experiences, and connect with other maintainers and community members.
