name: Continuous Integration

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: oracle

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "beta"

      - name: Enter to the flutter project directory
        run: cd mobile/nairobitrafficpcb
