name: Spell Check

on:
  push:
  pull_request:
  schedule:
    - cron: "0 6 * * 0"
  workflow_dispatch:
  repository_dispatch:

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Spell check
        uses: codespell-project/actions-codespell@v2
